version: "3"

tasks:
  default:
    cmds:
      - task -l

  run_regression_tests:
    desc: "running regression tests"
    cmds:
      - echo "running regression tests..."
      - go test -tags=regression ./...
    dir: .
    env:
      CLIENT_ONE_URL: "{{.CLIENT_ONE_URL}}"
      CLIENT_TWO_URL: "{{.CLIENT_TWO_URL}}"
      CLIENT_ONE_LEADER_XPRIV: "{{.CLIENT_ONE_LEADER_XPRIV}}"
      CLIENT_TWO_LEADER_XPRIV: "{{.CLIENT_TWO_LEADER_XPRIV}}"
