.PHONY: admin_add_user
admin_add_user:
	@echo "running admin_add_user..."
	@go run ./admin_add_user/admin_add_user.go

.PHONY: admin_remove_user
admin_remove_user:
	@echo "running admin_remove_user..."
	@go run ./admin_remove_user/admin_remove_user.go

.PHONY: create_transaction
create_transaction:
	@echo "running create_transaction..."
	@go run ./create_transaction/create_transaction.go

# .PHONY: custom_logger
# custom_logger:
# 	@echo "running custom_logger..."
# 	@go run ./custom_logger/custom_logger.go

.PHONY: generate_keys
generate_keys:
	@echo "running generate_keys..."
	@go run ./generate_keys/generate_keys.go

.PHONY: get_balance
get_balance:
	@echo "running get_balance..."
	@go run ./get_balance/get_balance.go

.PHONY: handle_exceptions
handle_exceptions:
	@echo "running handle_exceptions..."
	@go run ./handle_exceptions/handle_exceptions.go

.PHONY: list_transactions
list_transactions:
	@echo "running list_transactions..."
	@go run ./list_transactions/list_transactions.go

.PHONY: send_op_return
send_op_return:
	@echo "running send_op_return..."
	@go run ./send_op_return/send_op_return.go

.PHONY: xpriv_from_mnemonic
xpriv_from_mnemonic:
	@echo "running xpriv_from_mnemonic..."
	@go run ./xpriv_from_mnemonic/xpriv_from_mnemonic.go

.PHONY: xpub_from_xpriv
xpub_from_xpriv:
	@echo "running xpub_from_xpriv..."
	@go run ./xpub_from_xpriv/xpub_from_xpriv.go
