---
version: "3"

tasks:
  admin_add_user:
    desc: "running admin_add_user..."
    cmds:
      - echo "running admin_add_user..."
      - go run ./admin_add_user/admin_add_user.go

  admin_remove_user:
    desc: "running admin_remove_user..."
    cmds:
      - echo "running admin_remove_user..."
      - go run ./admin_remove_user/admin_remove_user.go

  create_transaction:
    desc: "running create_transaction..."
    cmds:
      - echo "running create_transaction..."
      - go run ./create_transaction/create_transaction.go

  generate_keys:
    desc: "running generate_keys..."
    cmds:
      - echo "running generate_keys..."
      - go run ./generate_keys/generate_keys.go

  get_balance:
    desc: "running get_balance..."
    cmds:
      - echo "running get_balance..."
      - go run ./get_balance/get_balance.go

  handle_exceptions:
    desc: "running handle_exceptions..."
    cmds:
      - echo "running handle_exceptions..."
      - go run ./handle_exceptions/handle_exceptions.go

  list_transactions:
    desc: "running list_transactions..."
    cmds:
      - echo "running list_transactions..."
      - go run ./list_transactions/list_transactions.go

  send_op_return:
    desc: "running send_op_return..."
    cmds:
      - echo "running send_op_return..."
      - go run ./send_op_return/send_op_return.go

  xpriv_from_mnemonic:
    desc: "running xpriv_from_mnemonic..."
    cmds:
      - echo "running xpriv_from_mnemonic..."
      - go run ./xpriv_from_mnemonic/xpriv_from_mnemonic.go

  xpub_from_xpriv:
    desc: "running xpub_from_xpriv..."
    cmds:
      - echo "running xpub_from_xpriv..."
      - go run ./xpub_from_xpriv/xpub_from_xpriv.go
  generate_totp:
    desc: "running generate_totp..."
    cmds:
      - echo "running generate_totp..."
      - go run ./generate_totp/generate_totp.go
  webhooks:
    desc: "running webhooks..."
    cmds:
      - echo "running webhooks..."
      - go run ./webhooks/webhooks.go
