version: "3"

tasks:
  default:
    cmds:
      - task --list
    desc: "Display all available tasks."

  access_key:
    desc: "Fetch Access key as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./access_key/access_key.go
      - echo "=================================================================="

  admin_add_user:
    desc: "Add user as Admin."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./admin_add_user/admin_add_user.go
      - echo "=================================================================="

  admin_remove_paymail:
    desc: "Remove paymail as Admin."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./admin_remove_paymail/admin_remove_paymail.go
      - echo "=================================================================="

  create_transaction:
    desc: "Create transaction as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./create_transaction/create_transaction.go
      - echo "=================================================================="

  generate_keys:
    desc: "Generate keys for SPV Wallet API access."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ../walletkeys/cmd/main.go
      - echo "=================================================================="

  get_balance:
    desc: "Get balance as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./get_balance/get_balance.go
      - echo "=================================================================="

  get_shared_config:
    desc: "Get shared config as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./get_shared_config/get_shared_config.go
      - echo "=================================================================="

  list_access_keys:
    desc: "Fetch first page of access keys as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./list_access_keys/list_access_keys.go
      - echo "=================================================================="

  list_transactions:
    desc: "Fetch first page of transactions as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./list_transactions/list_transactions.go
      - echo "=================================================================="

  manage_contacts:
    desc: "Show possible contact scenario with TOTP generation&validation"
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./manage_contacts/manage_contacts.go
      - echo "=================================================================="

  send_op_return:
    desc: "Create draft transaction, finalize transaction and record transaction as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./send_op_return/send_op_return.go
      - echo "=================================================================="

  sync_merkleroots:
    desc: "Sync Merkle roots as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./sync_merkleroots/sync_merkleroots.go
      - echo "=================================================================="

  update_user_xpub_metadata:
    desc: "Update xPub metadata as User."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./update_user_xpub_metadata/update_user_xpub_metadata.go
      - echo "=================================================================="

  xpriv_from_mnemonic:
    desc: "Extract xPriv from mnemonic."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./xpriv_from_mnemonic/xpriv_from_mnemonic.go
      - echo "=================================================================="

  xpub_from_xpriv:
    desc: "Extract xPub from xPriv."
    silent: true
    cmds:
      - echo "=================================================================="
      - go run ./xpub_from_xpriv/xpub_from_xpriv.go
      - echo "=================================================================="
