package constants

const (
	AdminUtxosAPI        = "admin/utxos"
	AdminContactsAPI     = "admin/contacts"
	AdminXPubsAPI        = "admin/xpubs"
	AdminSharedConfigAPI = "admin/shared-config"
	AdminInvitationsAPI  = "admin/invitations"
	AdminTransactionsAPI = "admin/transactions"
	AdminAccessKeyAPI    = "admin/access-key"
	AdminWebhooksAPI     = "admin/webhooks"
	AdminPaymailAPI      = "admin/paymail"
	AdminStatusAPI       = "admin/status"
	AdminStatsAPI        = "admin/stats"
	UserTransactionsAPI  = "user/transactions"
	UserUtxosAPI         = "user/utxos"
	UserContactsAPI      = "user/contacts"
	UserXPubsAPI         = "user/xpubs"
	UserSharedConfigAPI  = "user/shared-config"
	UserInvitationsAPI   = "user/invitations"
	UserAccessKeyAPI     = "user/access-key"
	UserWebhooksAPI      = "user/webhooks"
	UserPaymailAPI       = "user/paymail"
	UserStatusAPI        = "user/status"
	UserStatsAPI         = "user/stats"
	UserMerkleRootAPI    = "user/merkle-root"
)
