name: "Regression Tests"
run-name: "Regression Tests for client-v2 (${{ inputs.go_client_branch }}) | ID: ${{ github.run_id }}-${{ github.run_attempt }}"

on:
  workflow_dispatch:
    inputs:
      go_client_branch:
        description: 'Branch to use for the Go client'
        required: true
        default: 'main'
        type: string
      keep_instances:
        description: 'When should it keep instances created during tests?'
        required: true
        default: 'never'
        type: choice
        options:
          - 'always'
          - 'failure'
          - 'never'
  pull_request_target:
    types: [labeled]

jobs:
  test:
    uses: 4chain-ag/spv-wallet-regression/.github/workflows/run-regression-tests.yaml@test-regression-tests-on-client-v2
    with:
      image_tag: ${{ needs.release.outputs.imageVersion }}
      run_id: '${{ github.run_id }}-${{ github.run_attempt }}'
      keep_instances: ${{ inputs.keep_instances }}
      go_client_ref: ${{ inputs.go_client_branch }}
      run_js_client_tests: false
    secrets:
      MASTER_INSTANCE_URL: ${{ secrets.REG_MASTER_INSTANCE_URL }}
      MASTER_INSTANCE_XPRIV: ${{ secrets.REG_MASTER_INSTANCE_XPRIV }}
      BLOCK_HEADERS_SERVICE_URL: ${{ secrets.REG_BLOCK_HEADERS_SERVICE_URL }}
      BLOCK_HEADERS_SERVICE_AUTH_TOKEN: ${{ secrets.REG_BLOCK_HEADERS_SERVICE_AUTH_TOKEN }}
      ARGOCD_SERVER: ${{ secrets.REG_ARGOCD_SERVER }}
      ARGOCD_USERNAME: ${{ secrets.REG_ARGOCD_USERNAME }}
      ARGOCD_PASSWORD: ${{ secrets.REG_ARGOCD_PASSWORD }}
